gems: [jekyll-paginate]

# Site settings
title: John Wong's Blog
email: huangxiaozhe1988@gmail.com
description: > # John Wong's Blog.
placeholder: //dn-johnwong.qbox.me/images/octocat-180.png
# baseurl: /blog/ # the subpath of your site, e.g. /blog/
# url: "http://localhost" # the base hostname & protocol for your site

exclude:
  - README.md
  - .travis.yml
  - Gemfile
  - vendor

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

# Pagination
paginate: 20
paginate_path: ":num/"

# Extent settings
username: John Wong
motto: 一个热爱编程的傻瓜
gravatar_hash: 107ce8be1c08392d453302506e5e5bfa # used for gravater
category_info: 
    - {name: "mobile", color: "#62bb47", icon: glyphicon-phone}
    # - {name: security, color: "#fbb726", icon: glyphicon-eye-open, note: "[只是解闷<a href='http://wooyun.org/whitehats/JohnWong'>JohnWong@乌云</a>]"}
    - {name: "showcase", color: "#943b95", icon: glyphicon-film, note: "[课余时间玩的东西]"}
    - {name: "nonetech", color: "#e03a3e", icon: glyphicon-hand-right, note: "[只谈非技术]"}
    # - {name: "front end", color: "#943b95", icon: glyphicon-link}
    - {name: "past", color: "#a9b7b7", icon: glyphicon-time, note: "[迁移自旧博客]"}
    - {name: "bookmark"}

cdnhost: "//dn-johnwong.qbox.me/"

# Github
github:
    url: "https://github.com/"
    username: "JohnWong"
    followers: 68
    starred: 600
    following: 58
